import { describe, it, expect, vi, beforeEach } from "vitest";
import { DartLanguageAdapter } from "./dart.js";
import { vol } from "memfs";
import type { fs } from "memfs";
import { cachedFetch } from "../cached-fetch.js";
import type { Workspace } from "../workspace.js";

vi.mock("../cached-fetch.js");

vi.mock("fs/promises", async () => {
  const memfs: { fs: typeof fs } = await vi.importActual("memfs");
  return memfs.fs.promises;
});

vi.mock("fs", async () => {
  const memfs: { fs: typeof fs } = await vi.importActual("memfs");
  return memfs.fs;
});

describe("DartLanguageAdapter", () => {
  beforeEach(() => {
    vol.reset();
  });

  describe("discover", () => {
    const tests = [
      {
        desc: "should return not detected if pubspec.yaml is not found",
        files: {},
        expected: {
          detected: false,
          name: "dart",
          packages: [],
        },
      },
      {
        desc: "should return detected for basic Dart project",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_dart_app
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  http: ^0.13.5
`,
        },
        expected: {
          detected: true,
          name: "dart",
          packageManager: "pub",
          runtime: "dart",
          runtimeVersion: ">=2.17.0 <4.0.0",
          packages: [],
        },
      },
      {
        desc: "should detect Flutter project",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_flutter_app
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
`,
        },
        expected: {
          detected: true,
          name: "flutter",
          packageManager: "pub",
          runtime: "flutter",
          runtimeVersion: ">=2.17.0 <4.0.0",
          packages: [],
        },
      },
      {
        desc: "should discover packages with guides using pubspec.lock",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_dart_app
dependencies:
  package_a: ^1.0.0
dev_dependencies:
  test: ^1.21.0
`,
          "/test/workspace/pubspec.lock": `
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  package_a:
    dependency: "direct main"
    description:
      name: package_a
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: def456
      url: "https://pub.dev"
    source: hosted
    version: "1.21.0"
`,
          "/home/.pub-cache/hosted/pub.dev/package_a-1.0.0/.guides/config.json": "{}",
          "/home/.pub-cache/hosted/pub.dev/dotguides_contrib_test-1.21.0/.guides/config.json": "{}",
        },
        expected: {
          detected: true,
          name: "dart",
          packageManager: "pub",
          runtime: "dart",
          packages: ["package_a", "test"],
        },
      },
      {
        desc: "should handle scoped packages",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_dart_app
dependencies:
  some_package: ^1.0.0
`,
          "/test/workspace/pubspec.lock": `
packages:
  some_package:
    dependency: "direct main"
    description:
      name: some_package
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
`,
          "/home/.pub-cache/hosted/pub.dev/dotguides_contrib_some_package-1.0.0/.guides/config.json": "{}",
        },
        expected: {
          detected: true,
          name: "dart",
          packageManager: "pub",
          runtime: "dart",
          packages: ["some_package"],
        },
      },
      {
        desc: "should discover local path packages",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_dart_app
dependencies:
  loudify:
    path: /Users/sethladd/Code/loudify/loudify
`,
          "/test/workspace/pubspec.lock": `
packages:
  loudify:
    dependency: "direct main"
    description:
      path: "/Users/sethladd/Code/loudify/loudify"
      relative: false
    source: path
    version: "1.0.0"
`,
          "/Users/sethladd/Code/loudify/loudify/.guides/config.json": "{}",
        },
        expected: {
          detected: true,
          name: "dart",
          packageManager: "pub",
          runtime: "dart",
          packages: ["loudify"],
        },
      },
      {
        desc: "should parse dependencies correctly",
        files: {
          "/test/workspace/pubspec.yaml": `
name: my_app
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.1
  
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.21.0

dependency_overrides:
  meta: ^1.9.1
`,
          "/test/workspace/pubspec.lock": `
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      sha256: def456
      url: "https://pub.dev"
    source: hosted
    version: "4.8.1"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      sha256: ghi789
      url: "https://pub.dev"
    source: hosted
    version: "2.4.6"
  json_serializable:
    dependency: "direct dev"
    description:
      name: json_serializable
      sha256: jkl012
      url: "https://pub.dev"
    source: hosted
    version: "6.7.1"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: mno345
      url: "https://pub.dev"
    source: hosted
    version: "1.21.0"
  meta:
    dependency: override
    description:
      name: meta
      sha256: pqr678
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
`,
          "/home/.pub-cache/hosted/pub.dev/http-0.13.5/.guides/config.json": "{}",
          "/home/.pub-cache/hosted/pub.dev/dotguides_contrib_test-1.21.0/.guides/config.json": "{}",
        },
        expected: {
          detected: true,
          name: "dart",
          packageManager: "pub",
          runtime: "dart",
          runtimeVersion: ">=2.17.0 <4.0.0",
          packages: ["http", "test"],
        },
      },
    ];

    it.each(tests)("$desc", async ({ files, expected }) => {
      vol.fromJSON(files);
      
      // Set HOME environment variable for tests that use pub cache
      const originalHome = process.env.HOME;
      process.env.HOME = "/home";
      
      try {
        const adapter = new DartLanguageAdapter();
        const context = await adapter.discover("/test/workspace");
        
        expect(context.detected).toBe(expected.detected);
        expect(context.name).toBe(expected.name);
        expect(context.packageManager).toBe(expected.packageManager);
        expect(context.runtime).toBe(expected.runtime);
        if (expected.runtimeVersion) {
          expect(context.runtimeVersion).toBe(expected.runtimeVersion);
        }
        expect(context.packages.sort()).toEqual(expected.packages.sort());
      } finally {
        // Restore original HOME environment variable
        if (originalHome !== undefined) {
          process.env.HOME = originalHome;
        } else {
          delete process.env.HOME;
        }
      }
    });
  });

  describe("loadPackage", () => {
    it("should load a package with guides from pub cache", async () => {
      const originalHome = process.env.HOME;
      process.env.HOME = "/home";
      
      try {
        vol.fromJSON({
          "/test/workspace/pubspec.lock": `
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
`,
          "/home/.pub-cache/hosted/pub.dev/http-0.13.5/.guides/config.json": "{}",
        });

        const adapter = new DartLanguageAdapter();
        const workspace = {
          directories: ["/test/workspace"],
          languages: [{ packages: ["http"] }],
        } as unknown as Workspace;
        const pkg = await adapter.loadPackage(
          workspace,
          "/test/workspace",
          "http"
        );
        expect(pkg.name).toBe("http");
      } finally {
        if (originalHome !== undefined) {
          process.env.HOME = originalHome;
        } else {
          delete process.env.HOME;
        }
      }
    });

    it("should load a contrib package from pub cache", async () => {
      const originalHome = process.env.HOME;
      process.env.HOME = "/home";
      
      try {
        vol.fromJSON({
          "/test/workspace/pubspec.lock": `
packages:
  dio:
    dependency: "direct main"
    description:
      name: dio
      sha256: def456
      url: "https://pub.dev"
    source: hosted
    version: "5.3.2"
`,
          "/home/.pub-cache/hosted/pub.dev/dotguides_contrib_dio-5.3.2/.guides/config.json": "{}",
        });

        const adapter = new DartLanguageAdapter();
        const workspace = {
          directories: ["/test/workspace"],
          languages: [{ packages: ["dio"] }],
        } as unknown as Workspace;
        const pkg = await adapter.loadPackage(
          workspace,
          "/test/workspace",
          "dio"
        );
        expect(pkg.name).toBe("dio");
      } finally {
        if (originalHome !== undefined) {
          process.env.HOME = originalHome;
        } else {
          delete process.env.HOME;
        }
      }
    });

    it("should throw error if pubspec.lock not found", async () => {
      vol.fromJSON({});

      const adapter = new DartLanguageAdapter();
      const workspace = {
        directories: ["/test/workspace"],
        languages: [{ packages: ["nonexistent"] }],
      } as unknown as Workspace;
      
      await expect(adapter.loadPackage(
        workspace,
        "/test/workspace",
        "nonexistent"
      )).rejects.toThrow("Could not find pubspec.lock for package nonexistent");
    });

    it("should load a local path package", async () => {
      vol.fromJSON({
        "/test/workspace/pubspec.lock": `
packages:
  loudify:
    dependency: "direct main"
    description:
      path: "/Users/sethladd/Code/loudify/loudify"
      relative: false
    source: path
    version: "1.0.0"
`,
        "/Users/sethladd/Code/loudify/loudify/.guides/config.json": "{}",
      });

      const adapter = new DartLanguageAdapter();
      const workspace = {
        directories: ["/test/workspace"],
        languages: [{ packages: ["loudify"] }],
      } as unknown as Workspace;
      const pkg = await adapter.loadPackage(
        workspace,
        "/test/workspace",
        "loudify"
      );
      expect(pkg.name).toBe("loudify");
    });

    it("should throw error if package not in lock file", async () => {
      vol.fromJSON({
        "/test/workspace/pubspec.lock": `
packages:
  other_package:
    dependency: "direct main"
    description:
      name: other_package
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
`,
      });

      const adapter = new DartLanguageAdapter();
      const workspace = {
        directories: ["/test/workspace"],
        languages: [{ packages: ["nonexistent"] }],
      } as unknown as Workspace;
      
      await expect(adapter.loadPackage(
        workspace,
        "/test/workspace",
        "nonexistent"
      )).rejects.toThrow("Package nonexistent not found in pubspec.lock");
    });

    it("should throw error for unsupported source type", async () => {
      vol.fromJSON({
        "/test/workspace/pubspec.lock": `
packages:
  git_package:
    dependency: "direct main"
    description:
      url: "https://github.com/example/repo.git"
      ref: main
    source: git
    version: "1.0.0"
`,
      });

      const adapter = new DartLanguageAdapter();
      const workspace = {
        directories: ["/test/workspace"],
        languages: [{ packages: ["git_package"] }],
      } as unknown as Workspace;
      
      await expect(adapter.loadPackage(
        workspace,
        "/test/workspace",
        "git_package"
      )).rejects.toThrow("Package git_package has unsupported source type: git");
    });
  });

  describe("discoverContrib", () => {
    describe("with DOTGUIDES_CONTRIB", () => {
      const tests = [
        {
          desc: "should discover nothing if no packages match",
          packages: ["package_a", "package_b"],
          files: {},
          expected: [],
        },
        {
          desc: "should discover a single package",
          packages: ["package_a", "package_b"],
          files: {
            "/contrib/dart/package_a/index.dart": "",
          },
          expected: ["file:/contrib/dart/package_a"],
        },
        {
          desc: "should discover multiple packages",
          packages: ["package_a", "package_b", "package_c"],
          files: {
            "/contrib/dart/package_a/index.dart": "",
            "/contrib/dart/package_c/index.dart": "",
          },
          expected: ["file:/contrib/dart/package_a", "file:/contrib/dart/package_c"],
        },
      ];

      beforeEach(() => {
        process.env.DOTGUIDES_CONTRIB = "/contrib";
      });

      it.each(tests)("$desc", async ({ packages, files, expected }) => {
        vol.fromJSON(files);
        const adapter = new DartLanguageAdapter();
        const result = await adapter.discoverContrib(packages);
        expect(result.sort()).toEqual(expected.sort());
      });
    });

    describe("with pub.dev", () => {
      const tests = [
        {
          desc: "should discover nothing if no packages match",
          packages: ["package_a", "package_b"],
          found: [],
          expected: [],
        },
        {
          desc: "should discover a single package",
          packages: ["package_a", "package_b"],
          found: ["package_a"],
          expected: ["package_a"],
        },
        {
          desc: "should discover multiple packages",
          packages: ["package_a", "package_b", "package_c"],
          found: ["package_a", "package_c"],
          expected: ["package_a", "package_c"],
        },
      ];

      beforeEach(() => {
        delete process.env.DOTGUIDES_CONTRIB;
      });

      it.each(tests)("$desc", async ({ packages, found, expected }) => {
        vi.mocked(cachedFetch).mockImplementation(async (url) => {
          const pkg = url
            .toString()
            .replace("https://pub.dev/packages/dotguides_contrib_", "");
          if (found.includes(pkg)) {
            return new Response(null, { status: 200 });
          }
          return new Response(null, { status: 404 });
        });
        const adapter = new DartLanguageAdapter();
        const result = await adapter.discoverContrib(packages);
        expect(result.sort()).toEqual(expected.sort());
      });
    });
  });

  describe("_parseLockFileDependencies", () => {
    it("should parse hosted and path dependencies from pubspec.lock", async () => {
      const originalHome = process.env.HOME;
      process.env.HOME = "/home";
      
      try {
        vol.fromJSON({
          "/test/workspace/pubspec.yaml": `
name: my_app
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.21.0
`,
          "/test/workspace/pubspec.lock": `
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
  json_annotation:
    dependency: "direct main"
    description:
      name: json_annotation
      sha256: def456
      url: "https://pub.dev"
    source: hosted
    version: "4.8.1"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: ghi789
      url: "https://pub.dev"
    source: hosted
    version: "1.21.0"
  my_local_package:
    dependency: "direct main"
    description:
      path: "/Users/sethladd/Code/my_local_package"
      relative: false
    source: path
    version: "1.0.0"
`,
        });

        const adapter = new DartLanguageAdapter();
        const context = await adapter.discover("/test/workspace");
        
        // The adapter should parse the lock file correctly
        expect(context.detected).toBe(true);
        expect(context.runtimeVersion).toBe(">=2.17.0 <4.0.0");
        // Since no actual .guides directories exist in the test, packages array should be empty
        expect(context.packages).toEqual([]);
      } finally {
        if (originalHome !== undefined) {
          process.env.HOME = originalHome;
        } else {
          delete process.env.HOME;
        }
      }
    });
  });
});
